(()=>{'use strict';
const $=s=>document.querySelector(s),msg=$('#portal-message');
let token=sessionStorage.getItem('ptn-admin')||'',challenge='',data={rows:[],students:[],lessons:[],feedback:[]};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=s=>s?new Date(s).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'}):'';
function say(s){msg.textContent=s}
async function request(p){return window.ptnRequest({...p,token})}
function login(){token='';sessionStorage.removeItem('ptn-admin');$('#admin-login').classList.remove('portal-hidden');$('#admin-content').classList.add('portal-hidden');data={rows:[],students:[],lessons:[],feedback:[]};['lead-list','student-list','lesson-list','feedback-list'].forEach(id=>$('#'+id).replaceChildren())}
$('#send-code').addEventListener('click',async()=>{const b=$('#send-code');b.disabled=true;say('Đang gửi mã tới email của chị…');try{const r=await request({action:'admin_otp'});challenge=r.challenge;$('#verify-form').classList.remove('portal-hidden');say('Đã gửi mã. Chị mở email, sao chép mã và nhập vào ô bên dưới.');$('#verify-form input').focus()}catch(e){say(e.message)}finally{b.disabled=false}});
$('#verify-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const r=await request({action:'admin_verify',challenge,code:e.target.elements.code.value});token=r.token;sessionStorage.setItem('ptn-admin',token);e.target.reset();await load()}catch(e){say(e.message)}finally{b.disabled=false}});
async function load(){say('Đang tải dữ liệu…');try{const r=await request({action:'list'});data=r;$('#admin-login').classList.add('portal-hidden');$('#admin-content').classList.remove('portal-hidden');$('#open-sheet').href=r.sheetUrl;render();say('Đã cập nhật lúc '+new Date().toLocaleTimeString('vi-VN'));}catch(e){if(/đăng nhập|hết hạn/.test(e.message))login();say(e.message)}}
$('#refresh-data').addEventListener('click',load);
$('#logout').addEventListener('click',async()=>{try{await request({action:'logout'})}catch{}login();say('Đã đăng xuất.')});
const states=['Mới đăng ký','Đang tư vấn','Đã xác nhận','Lưu trữ'];
function selectedRows(){const q=$('#search-leads').value.trim().toLocaleLowerCase('vi'),status=$('#filter-status').value,kind=$('#filter-kind').value;return data.rows.filter(r=>(!q||[r.name,r.phone,r.email,r.message].join(' ').toLocaleLowerCase('vi').includes(q))&&(!status||r.status===status)&&(!kind||r.kind===kind)).slice().reverse()}
function render(){
 $('#admin-stats').innerHTML=states.map(s=>`<div><strong>${data.rows.filter(r=>r.status===s).length}</strong><span>${esc(s)}</span></div>`).join('');renderLeads();renderStudents();renderLessons();renderFeedback();
}
function renderLeads(){const rows=selectedRows();$('#lead-list').innerHTML=rows.length?rows.map(r=>`<article class="portal-card"><div class="lead-meta"><span>${esc(r.id)}</span><span>${esc(date(r.created))}</span><span>${esc(r.kind)}</span></div><h2>${esc(r.name)}</h2><span class="lead-badge">${esc(r.status)}</span><p>${esc(r.phone)}${r.email?' · '+esc(r.email):''}</p><p class="lead-message">${esc(r.message)}</p>${r.appointment?`<p>Lịch đề xuất: ${esc(r.appointment)} · ${esc(r.channel)}</p>`:''}${r.notes?`<p class="lead-message">Ghi chú: ${esc(r.notes)}</p>`:''}${r.notification&&r.notification!=='Đã gửi'?'<p class="portal-status">Thông báo email chưa gửi được. Yêu cầu vẫn đã được lưu.</p>':''}<div class="portal-toolbar"><button class="button small" data-edit="${esc(r.id)}">Ghi chú &amp; trạng thái</button>${data.students.some(s=>s.leadId===r.id)?'<span>Đã có hồ sơ học viên</span>':`<button class="button small" data-enroll="${esc(r.id)}">Tạo học viên</button>`}</div></article>`).join(''):'<div class="portal-card">Chưa có yêu cầu phù hợp. Các form gửi thành công sẽ xuất hiện ở đây và trong Google Sheets.</div>'}
['search-leads','filter-status','filter-kind'].forEach(id=>$('#'+id).addEventListener('input',renderLeads));
const dialog=$('#edit-dialog'),editor=$('#editor-body');$('#close-editor').addEventListener('click',()=>dialog.close());
function openEditor(html,submit){editor.innerHTML=html;dialog.showModal();const f=editor.querySelector('form');if(f)f.addEventListener('submit',async e=>{e.preventDefault();const b=f.querySelector('button[type=submit]');b.disabled=true;const error=f.querySelector('[role=status]');try{await submit(Object.fromEntries(new FormData(f)),f)}catch(e){error.textContent=e.message}finally{b.disabled=false}})}
const options=(arr,v)=>arr.map(s=>`<option${s===v?' selected':''}>${esc(s)}</option>`).join('');
const end='<p role="status" aria-live="polite"></p><button type="submit" class="button">Lưu thay đổi</button></form>';
$('#lead-list').addEventListener('click',e=>{const edit=e.target.closest('[data-edit]'),enroll=e.target.closest('[data-enroll]');if(edit){const r=data.rows.find(r=>r.id===edit.dataset.edit);openEditor(`<h2>${esc(r.name)}</h2><form><label>Trạng thái<select name="status">${options(states,r.status)}</select></label><label>Ghi chú<textarea name="notes" rows="5" maxlength="4000">${esc(r.notes)}</textarea></label>${end}`,async p=>{await request({action:'update',id:r.id,updated:r.updated,...p});dialog.close();await load()})}if(enroll){const r=data.rows.find(r=>r.id===enroll.dataset.enroll);openEditor(`<h2>Tạo hồ sơ: ${esc(r.name)}</h2><p>Học viên được tạo ở trạng thái Chờ xác nhận. Chị có thể mở quyền học sau.</p><form><label>Lớp học<input name="group" maxlength="100" placeholder="Tên lớp do chị quản lý"></label>${end}`,async p=>{const result=await request({action:'enroll',id:r.id,...p});showCode(result.code);await load()})}});
function showCode(code){editor.innerHTML='<h2>Mã truy cập riêng của học viên</h2><p>Chị sao chép và gửi riêng cho đúng học viên. Mã chỉ hiển thị khi cấp; có thể cấp lại trong hồ sơ.</p><pre>'+esc(code)+'</pre><button class="button" id="copy-student-code">Sao chép mã</button><p role="status"></p>';$('#copy-student-code').addEventListener('click',async()=>{try{await navigator.clipboard.writeText('Vào học: https://phamthanhnhue.vn/hoc-vien.html\nMã truy cập: '+code);editor.querySelector('[role=status]').textContent='Đã sao chép.'}catch{editor.querySelector('[role=status]').textContent='Chị chọn và sao chép mã bên trên.'}})}
function renderStudents(){$('#student-list').innerHTML=data.students.length?data.students.map(s=>`<article class="portal-card"><span class="lead-badge">${esc(s.status)}</span><h2>${esc(s.name)}</h2><p>${esc(s.phone)} · ${esc(s.email)}</p><p>Lớp: ${esc(s.group||'Chưa xếp lớp')}</p><p class="lead-message">${esc(s.notes)}</p><button class="button small" data-student="${esc(s.id)}">Quản lý học viên</button></article>`).join(''):'<div class="portal-card">Chưa có học viên. Mở mục Đăng ký &amp; tư vấn rồi chọn Tạo học viên.</div>'}
$('#student-list').addEventListener('click',e=>{const b=e.target.closest('[data-student]');if(!b)return;const s=data.students.find(x=>x.id===b.dataset.student);openEditor(`<h2>${esc(s.name)}</h2><form><label>Trạng thái học<select name="status">${options(['Chờ xác nhận','Đang học','Tạm dừng','Hoàn thành'],s.status)}</select></label><label>Lớp học<input name="group" value="${esc(s.group)}" maxlength="100"></label><label>Ghi chú<textarea name="notes" rows="4" maxlength="4000">${esc(s.notes)}</textarea></label><label><input name="resetCode" type="checkbox">Cấp lại mã truy cập (mã cũ sẽ hết hiệu lực)</label>${end}`,async p=>{const result=await request({action:'student_update',id:s.id,updated:s.updated,...p,resetCode:p.resetCode==='on'});if(result.code)showCode(result.code);else dialog.close();await load()})});
function renderLessons(){$('#lesson-list').innerHTML=data.lessons.length?data.lessons.map(l=>`<article class="portal-card"><span class="lead-badge">${l[6]==='Có'?'Đã công bố':'Bản nháp'}</span><h2>${esc(l[2])}</h2><p>Lớp: ${esc(l[1])} · Thứ tự: ${esc(l[5])}</p><button class="button small" data-lesson="${esc(l[0])}">Chỉnh sửa</button></article>`).join(''):'<div class="portal-card">Chưa có bài học. Chị có thể thêm nội dung và đường dẫn tài liệu của mình.</div>'}
function editLesson(l=['','','','','',1,'Không']){openEditor(`<h2>${l[0]?'Sửa':'Thêm'} bài học</h2><form><label>Lớp học<input name="group" required maxlength="100" value="${esc(l[1])}"></label><label>Tiêu đề<input name="title" required maxlength="200" value="${esc(l[2])}"></label><label>Hướng dẫn<textarea name="content" rows="5" maxlength="6000">${esc(l[3])}</textarea></label><label>Liên kết tài liệu<input type="url" name="url" value="${esc(l[4])}" placeholder="https://"></label><label>Thứ tự<input type="number" name="order" value="${esc(l[5])}"></label><label><input type="checkbox" name="published" ${l[6]==='Có'?'checked':''}>Công bố cho học viên trong lớp</label>${end}`,async p=>{await request({action:'lesson_save',id:l[0],...p,published:p.published==='on'});dialog.close();await load()})}
$('#new-lesson').addEventListener('click',()=>editLesson());$('#lesson-list').addEventListener('click',e=>{const b=e.target.closest('[data-lesson]');if(b)editLesson(data.lessons.find(l=>l[0]===b.dataset.lesson))});
function renderFeedback(){$('#feedback-list').innerHTML=data.feedback.length?data.feedback.map(f=>`<article class="portal-card"><span class="lead-badge">${esc(f[4])}</span><h2>${esc(data.students.find(s=>s.id===f[1])?.name||f[1])}</h2><p class="lead-message">${esc(f[2])}</p><p>Cho phép công bố: ${esc(f[3])}</p>${f[3]==='Có'?`<button class="button small" data-feedback="${esc(f[0])}">${f[4]==='Đã duyệt'?'Bỏ duyệt':'Duyệt cảm nhận'}</button>`:''}</article>`).join(''):'<div class="portal-card">Chưa có cảm nhận từ học viên.</div>'}
$('#feedback-list').addEventListener('click',async e=>{const b=e.target.closest('[data-feedback]');if(!b)return;const f=data.feedback.find(f=>f[0]===b.dataset.feedback);b.disabled=true;try{await request({action:'feedback_review',id:f[0],approved:f[4]!=='Đã duyệt'});await load()}catch(e){say(e.message)}finally{b.disabled=false}});
$('.admin-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-panel]');if(!b)return;document.querySelectorAll('[data-panel]').forEach(t=>{const selected=t===b;t.setAttribute('aria-selected',String(selected));$('#'+t.dataset.panel+'-panel').classList.toggle('portal-hidden',!selected)})});
$('#export-data').addEventListener('click',()=>{const keys=['id','created','kind','name','phone','email','message','appointment','channel','status','notes'];const cell=x=>'"'+String(x??'').replace(/^[=+\-@\t\r]/,"'$&").replaceAll('"','""')+'"';const rows=[['Mã','Ngày đăng ký','Loại','Họ tên','Điện thoại','Email','Nội dung','Lịch đề xuất','Kênh','Trạng thái','Ghi chú'],...selectedRows().map(r=>keys.map(k=>r[k]))];const blob=new Blob(['\ufeff'+rows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='dang-ky-pham-thanh-nhue.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
if(token)load();
})();
