(() => {
'use strict';
const API='https://pham-thanh-nhue-crm.hoctap-thanhnhue.chatgpt.site/api';
const el=id=>document.getElementById(id), login=el('login-form');
let session='',username='',rows=[],selected=null,setupCode='';
try{session=sessionStorage.getItem('ptn-crm-session')||''}catch{}
window.addEventListener('hashchange',()=>{if(/^[a-f0-9]{64}$/.test(new URLSearchParams(location.hash.slice(1)).get('thiet-lap')||''))location.reload()});
const hash=new URLSearchParams(location.hash.slice(1));if(/^[a-f0-9]{64}$/.test(hash.get('thiet-lap')||'')){setupCode=hash.get('thiet-lap');history.replaceState(null,'',location.pathname);el('login-title').textContent='Tạo tài khoản của chị';el('login-description').textContent='Đặt tên tài khoản và mật khẩu để sử dụng CRM.';el('setup-fields').hidden=false;login.elements.confirm.required=true;login.elements.password.minLength=15;login.elements.password.autocomplete='new-password';el('login-submit').textContent='Tạo tài khoản quản trị';}
function message(id,text='',error=false){const node=el(id);node.textContent=text;node.className=text?(error?'message-error':'message-success'):'';}
function setSession(data){session=data.token;username=data.username;try{sessionStorage.setItem('ptn-crm-session',session)}catch{}}
function signOut(){session='';username='';rows=[];selected=null;try{sessionStorage.removeItem('ptn-crm-session')}catch{}el('lead-rows').replaceChildren();el('dashboard').hidden=true;el('editor').hidden=true;el('logout').hidden=true;el('login-panel').hidden=false;login.reset();}
async function api(path,payload,method){const timer=new AbortController(),expiry=setTimeout(()=>timer.abort(),30000);try{const response=await fetch(API+path,{method:method||(payload?'POST':'GET'),credentials:'omit',headers:{...(payload?{'Content-Type':'application/json'}:{}),...(session?{Authorization:'Bearer '+session}:{})},body:payload?JSON.stringify(payload):undefined,signal:timer.signal});let data;try{data=await response.json()}catch{throw Error('Hệ thống đang được kết nối. Vui lòng thử lại sau ít phút.');}if(!response.ok){if(response.status===401&&session){signOut();message('login-message','Phiên đăng nhập đã kết thúc. Chị hãy đăng nhập lại.',true);}throw Error(data.error||'Chưa xử lý được yêu cầu.');}return data;}catch(e){if(e.name==='AbortError')throw Error('Kết nối chậm. Vui lòng thử lại.');if(e instanceof TypeError)throw Error('Chưa kết nối được hệ thống. Vui lòng kiểm tra mạng rồi thử lại.');throw e;}finally{clearTimeout(expiry)}}
async function showDashboard(){el('login-panel').hidden=true;el('dashboard').hidden=false;el('logout').hidden=false;el('signed-in').textContent='Tài khoản: '+username;await load();}
async function load(){el('reload').disabled=true;message('dashboard-message','Đang tải danh sách…');try{const data=await api('/leads');rows=data.rows;message('dashboard-message');render();}catch(e){message('dashboard-message',e.message,true)}finally{el('reload').disabled=false}}
const shown=()=>rows.filter(r=>(el('status-filter').value==='Tất cả'||r.status===el('status-filter').value)&&[r.name,r.phone,r.email,r.course].join(' ').toLocaleLowerCase('vi').includes(el('search').value.toLocaleLowerCase('vi')));
function node(tag,text,className){const n=document.createElement(tag);n.textContent=text;if(className)n.className=className;return n;}
function render(){el('count-all').textContent=rows.length;el('count-new').textContent=rows.filter(r=>r.status==='Mới đăng ký').length;el('count-consult').textContent=rows.filter(r=>r.status==='Đang tư vấn').length;el('count-learning').textContent=rows.filter(r=>r.status==='Đang học').length;const data=shown(),body=el('lead-rows');body.replaceChildren();el('empty').hidden=!!data.length;el('empty').textContent=rows.length?'Không có kết quả phù hợp. Chị thử từ khóa hoặc trạng thái khác.':'Chưa có đăng ký nào. Khi học viên gửi form, thông tin sẽ xuất hiện tại đây.';el('leads-table').hidden=!data.length;el('export').disabled=!data.length;for(const r of data){const tr=document.createElement('tr'),name=document.createElement('td'),contact=document.createElement('td'),state=document.createElement('td'),action=document.createElement('td');name.append(node('strong',r.name),node('small',r.course||r.kind));const phone=node('a',r.phone);phone.href='tel:'+r.phone.replace(/[^+0-9]/g,'');contact.append(phone,node('small',r.email));state.append(node('span',r.status,'status'));const button=node('button','Xem & cập nhật');button.addEventListener('click',()=>edit(r));action.append(button);tr.append(name,contact,state,node('td',new Date(r.created_at).toLocaleDateString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})),action);body.append(tr)}}
function edit(r){selected={...r};el('editor-name').textContent=r.name;el('editor-contact').textContent=r.phone+' · '+(r.email||'Chưa cung cấp email');el('editor-request').textContent=r.message;el('editor-appointment').textContent=r.appointment?'Lịch hẹn: '+r.appointment.replace('T',' ')+' (giờ Việt Nam) · '+r.channel:'';const f=el('edit-form');f.elements.status.value=r.status;f.elements.course.value=r.course;f.elements.notes.value=r.notes;message('edit-message');el('editor').hidden=false;el('editor').scrollIntoView({behavior:'smooth',block:'start'})}
login.addEventListener('submit',async e=>{e.preventDefault();if(setupCode&&login.elements.password.value!==login.elements.confirm.value){message('login-message','Hai mật khẩu chưa trùng nhau.',true);return;}el('login-submit').disabled=true;message('login-message');try{const data=await api('/auth',{action:setupCode?'setup':'login',username:login.elements.username.value,password:login.elements.password.value,...(setupCode?{code:setupCode}:{})});setSession(data);setupCode='';el('setup-fields').hidden=true;login.elements.confirm.required=false;login.elements.password.autocomplete='current-password';el('login-title').textContent='Đăng nhập';el('login-submit').textContent='Đăng nhập';login.reset();await showDashboard();}catch(e){message('login-message',e.message,true)}finally{el('login-submit').disabled=false}});
el('logout').addEventListener('click',async()=>{el('logout').disabled=true;try{await api('/auth',{action:'logout'});signOut();message('login-message','Đã đăng xuất.')}catch(e){message('dashboard-message','Chưa xác nhận được đăng xuất. Chị thử lại để kết thúc phiên trên hệ thống.',true)}finally{el('logout').disabled=false}});
el('reload').addEventListener('click',load);el('search').addEventListener('input',render);el('status-filter').addEventListener('change',render);el('close-editor').addEventListener('click',()=>{selected=null;el('editor').hidden=true;el('edit-form').reset()});
el('edit-form').addEventListener('submit',async e=>{e.preventDefault();if(!selected)return;const f=e.currentTarget;el('save').disabled=true;try{await api('/leads',{id:selected.id,updated_at:selected.updated_at,status:f.elements.status.value,course:f.elements.course.value,notes:f.elements.notes.value},'PATCH');selected=null;el('editor').hidden=true;f.reset();await load();message('dashboard-message','Đã lưu thông tin học viên.')}catch(e){message('edit-message',e.message,true)}finally{el('save').disabled=false}});
el('password-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,button=f.querySelector('button');if(f.elements.password.value!==f.elements.confirm.value){message('password-message','Hai mật khẩu mới chưa trùng nhau.',true);return;}button.disabled=true;try{const data=await api('/auth',{action:'password',username,currentPassword:f.elements.currentPassword.value,password:f.elements.password.value});setSession(data);f.reset();message('password-message','Đã đổi mật khẩu và đăng xuất các phiên khác.')}catch(e){message('password-message',e.message,true)}finally{button.disabled=false}});
el('export').addEventListener('click',()=>{const quote=v=>'"'+(/^[=+@\-\t\r]/.test(v)?"'":'')+String(v).replaceAll('"','""')+'"',data=[['Họ tên','Điện thoại','Email','Trạng thái','Lớp học','Nhu cầu','Ghi chú'],...shown().map(r=>[r.name,r.phone,r.email,r.status,r.course,r.message,r.notes])].map(r=>r.map(quote).join(',')).join('\r\n');const a=document.createElement('a'),url=URL.createObjectURL(new Blob(['\ufeff'+data],{type:'text/csv;charset=utf-8'}));a.href=url;a.download='hoc-vien-pham-thanh-nhue.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
if(session&&!setupCode){api('/auth').then(data=>{username=data.username;return showDashboard()}).catch(e=>{signOut();message('login-message',e.message,true)})}
})();
