(()=>{'use strict';const $=s=>document.querySelector(s),msg=$('#student-message');let token=sessionStorage.getItem('ptn-student')||'';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const request=p=>window.ptnRequest({...p,token});
function logout(){token='';sessionStorage.removeItem('ptn-student');$('#student-login').classList.remove('portal-hidden');$('#student-content').classList.add('portal-hidden');$('#student-lessons').replaceChildren();$('#student-greeting').textContent=''}
async function load(){msg.textContent='Đang tải…';try{const r=await request({action:'student_data'});$('#student-login').classList.add('portal-hidden');$('#student-content').classList.remove('portal-hidden');$('#student-greeting').textContent='Xin chào, '+r.name;$('#student-state').textContent='Trạng thái: '+r.status+(r.group?' · Lớp: '+r.group:'');$('#student-progress').textContent=r.lessons.length?'Đã hoàn thành '+r.lessons.filter(l=>r.completed.includes(l[0])).length+'/'+r.lessons.length+' bài học.':'';$('#student-lessons').innerHTML=r.lessons.length?r.lessons.map(l=>`<article class="portal-card lesson-card"><h2>${esc(l[2])}</h2><p>${esc(l[3])}</p>${/^https:\/\//i.test(l[4])?`<p><a href="${esc(l[4])}" target="_blank" rel="noopener">Mở tài liệu ↗</a></p>`:''}<label><input type="checkbox" data-lesson="${esc(l[0])}" ${r.completed.includes(l[0])?'checked':''}>Tôi đã hoàn thành bài này</label></article>`).join(''):'<div class="portal-card">Bài học sẽ hiển thị khi tài khoản được mở quyền và nội dung của lớp được công bố. <a href="tu-van.html">Liên hệ hỗ trợ</a>.</div>';$('#student-feedback').querySelector('button').disabled=!['Đang học','Hoàn thành'].includes(r.status);msg.textContent=''}catch(e){if(/đăng nhập|hết hạn|thay đổi/.test(e.message))logout();msg.textContent=e.message}}
$('#student-auth').addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const r=await request({action:'student_login',code:e.target.elements.code.value.trim()});token=r.token;sessionStorage.setItem('ptn-student',token);e.target.reset();await load()}catch(e){msg.textContent=e.message}finally{b.disabled=false}});
$('#student-refresh').addEventListener('click',load);$('#student-logout').addEventListener('click',()=>{logout();msg.textContent='Đã đăng xuất.'});
$('#student-lessons').addEventListener('change',async e=>{if(!e.target.matches('[data-lesson]'))return;const b=e.target;b.disabled=true;try{await request({action:'student_progress',lessonId:b.dataset.lesson,complete:b.checked});await load()}catch(e){b.checked=!b.checked;msg.textContent=e.message}finally{b.disabled=false}});
$('#student-feedback').addEventListener('submit',async e=>{e.preventDefault();const f=e.target,b=f.querySelector('button');b.disabled=true;try{await request({action:'student_feedback',message:f.elements.message.value,publish:f.elements.publish.checked});f.reset();msg.textContent='Đã tiếp nhận cảm nhận của bạn. Cảm ơn bạn đã chia sẻ.'}catch(e){msg.textContent=e.message}finally{b.disabled=false}});
if(token)load();})();
